@startuml

package org.sora.fx {
 class Application {
  +void start()
 }
}

package org.sora.fx.beans {
 class AppGuiConfiguration {
  +String nameCssConverter(String part)
  +String nameFxmlConverter(String part)
 }

 interface FormInterface {
  Scene getScene();
  String getView();
  String getResource();
 }

 class MainFormBean {
  +MainFormBean(String viewName, String mainResource)
 }

 class MainScreenController {
  +void initialize(URL location, ResourceBundle resources)
 }

 class MainScreenConfiguration {
  +void initMainScreen(Stage stage)
 }
}

MainFormBean -down-|> FormInterface

MainFormBean -> AppGuiConfiguration

MainScreenConfiguration -> FormInterface

@enduml